---
- name: Proxmox Node Setup
  hosts: hosts
  become: yes  # Dit zorgt ervoor dat de taken met sudo worden uitgevoerd

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker.io
      apt:
        name: docker.io
        state: present

    - name: Install Docker via Snap
      command: snap install docker

