
---
- hosts: proxmox
  tasks:

    # Voeg de rest van je playbook toe, inclusief het maken van de VM en cloud-init-configuratie
    - name: Create a Proxmox VM
      shell: qm create 100 --name MyVM --memory 2048 --sockets 1 --cores 2 --net0 model=virtio,bridge=vmbr0 --storage <opslag>
    - name: Create the directory /var/lib/vz/snippets if it doesn't exist
      file:
        path: /var/lib/vz/snippets
        state: directory
      become: yes  # Zorg ervoor dat je als beheerder (root) uitvoert
    - name: Add cloud-init configuration
      copy:
        content: |
          #cloud-config
          chpasswd: { expire: False }
          users:
            - name: <username>
              passwd: <wachtwoord>
              lock-passwd: false
          packages:
            - docker.io
          runcmd:
            - 'sudo apt-get update'
            - 'sudo apt-get install -y docker.io'
            - 'sudo systemctl enable docker'
            - 'sudo systemctl start docker'
        dest: /var/lib/vz/snippets/100.cloudinit
    - name: Apply cloud-init configuration
      shell: qm set 100 --cicustom "user=local:snippets/100.cloudinit"
    - name: Start the VM
      shell: qm start 100

