---
- hosts: proxmox
  tasks:

    - name: Create a Proxmox VM
      shell: qm create 100 --name MyVM --memory 4096 --sockets 1 --cores 4 --net0 model=virtio,bridge=vmbr0 --storage local-lvm --ide2 local-lvm:30
      become: yes

    - name: Set IP Address for the VM
      shell: qm set 100 --ipconfig0 ip=172.16.36.100/16,gw=172.16.0.1
      become: yes
    
    - name: Set DNS Server for the VM
      shell: qm set 100 --nameserver 172.16.0.1
      become: yes

    - name: Copy ISO file to VM
      command: qm importdisk 100 /mnt/pve/opslag/template/iso/ubuntu-23.04-desktop-amd64.iso opslag
      become: yes
    
    - name: Attach the iso to the VM
      command: qm set 100 -scsihw virtio-scsi-pci -scsi0 opslag:100/vm-100-disk-0.raw
      become: yes

    - name: Boot the Iso on the VM
      command: qm set 100 --boot c --bootdisk scsi0
      become: yes

    - name: Resize the disk to 35G
      command: qm resize 100 scsi0 +30G
      become: yes

    - name: Create the directory /var/lib/vz/snippets if it doesn't exist
      file:
        path: /var/lib/vz/snippets
        state: directory
      become: yes

    - name: Add cloud-init configuration
      copy:
        content: |
          #cloud-config
          chpasswd: { expire: False }
          users:
            - name: michael
              passwd: $6$mLj6eqwgy78hx6qB$qV7hYMBI1of4TOE.c0dMTruq8sUD0GobdKXm/R5K6ThiALi1kgj5se9fq.PWSws2l3aQoBscuo6H6wKhOuYNQQ0
              lock-passwd: false
          packages:
            - docker.io
          runcmd:
            - 'sudo apt-get update'
            - 'sudo apt-get install -y docker.io'
            - 'sudo systemctl enable docker'
            - 'sudo systemctl start docker'
        dest: /var/lib/vz/snippets/100.cloudinit
      become: yes

    - name: Apply cloud-init configuration
      shell: qm set 100 --cicustom "user=local:snippets/100.cloudinit"
      become: yes

    - name: Start the VM
      shell: qm start 100
      become: yes
