---
- name: Docker compose install
  hosts: hosts
  become: yes  # Dit zorgt ervoor dat de taken met sudo worden uitgevoerd

  tasks:
    - name: Create docker compose directory
      command: mkdir -p /usr/local/lib/docker/cli-plugins

    - name: download docker-compe-plugin
      command: curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins

    - name: chmod het
      command: chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

    - name: check version
      command: docker compose version