---
- name: Docker compose install
  hosts: vm
  become: yes  # Dit zorgt ervoor dat de taken met sudo worden uitgevoerd

  tasks:
    - name: Create docker compose directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'
      become: yes

    - name: download docker-compose plugin
      command: >
        curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64
        -o /usr/local/lib/docker/cli-plugins/docker-compose
      become: yes

    - name: chmod het
      command: chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
      become: yes