---
- name: Create docker subnet network
  hosts: swarm-master
  become: no

  tasks:
    - name: Create IPVLAN Network
      community.general.docker_network:
        name: opdracht2
        driver: ipvlan
        driver_options: {"ipvlan_mode": "l3", "parent": "eth0"}
        ipam_config:
          - subnet: 192.168.10.0/24
          - subnet: 192.168.20.0/24
        state: present
      register: create_network_result
    
    - name: Run MariaDB container 1
      community.general.docker_container:
        name: mariadb-subnet1
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: your_root_password
        ports:
          - "3307:3306"
        networks:
          - name: opdracht2
            ipv4_address: 192.168.10.2

    - name: Run MariaDB container 2
      community.general.docker_container:
        name: mariadb-subnet2
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: your_root_password
        ports:
          - "3308:3306"
        networks:
          - name: opdracht2
            ipv4_address: 192.168.20.2

    - name: Run Busybox container
      community.general.docker_container:
        name: busybox
        image: busybox
        command: /bin/sh
        interactive: yes
        auto_remove: true
        networks:
          - name: opdracht2
            ipv4_address: 192.168.20.3

- name: Add Static Routes to Hosts on Other Subnets
  hosts: localhost
  become: yes  

  tasks:
    - name: Add static routes for subnet1
      command: ip route add 192.168.10.0/24 via 172.16.36.100
      ignore_errors: yes  

    - name: Add static routes for subnet2
      command: ip route add 192.168.20.0/24 via 172.16.36.100
      ignore_errors: yes  